### ISSUE TITLE
Implementar cadastro de comentário por pauta

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera-app#10]

**Comment by evertonkrystian** [comment]
Esta issue, não poderia entrar no milestone "Melhorias de ambiente do aplicativo"? Assim com a issue #9 ?

**Comment by cabelotaina** [comment]
Hoje eh possivel fazer comentario sobre uma pauta bem como responder a um comentario e tambem encontrar o comentario que original a resposta por meio de um clique sobre o link para o pai do comentario.
