### ISSUE TITLE
Implementar cadastro de pauta

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera-app#11]

**Comment by evertonkrystian** [comment]
Como está o desenvolvimento deste cadastro? Esta issue já poderia ser fechada?

**Comment by cabelotaina** [comment]
Sim foi implementado um cadastro simples de pauta apenas com titulo e conteudo da pauta, por hora o usuario que  queira refinar a pauta tera que fazer as modificacoes na innterface web, no entanto em breve sera implementadas novas funcionalidades, as que permite uma pauta, como definir as etapas da pauta e relator.
