### ISSUE TITLE
pensar em forma alternativa de implementar o aplicativo mobile

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera-app#14]
Por termos tido alguns problemas com o login oauth2 do wordpress api, vamos tentar uma outra abordagem de login dentro do aplicativo

https://github.com/filp/react-native-es6-reflux

**Comment by diegorojas** [comment]
Vou terminar toda a interface do plugin do Delibera e fazer a revisão de tudo na versão mobile. Acho que podemos usar a interfaces do plugin mesmo no app. Vamos ver.

**Comment by evertonkrystian** [comment]
Como ficaram definidas as linhas de desenvolvimento após a execução desta issue?

**Comment by cabelotaina** [comment]
Foi criado a um novo grupo que assumiu o processo de desenvolvimento, utilizamos para resolver o problema do login wp-ouath-1 e ionic, na ultima versao.
