### ISSUE TITLE
Criar build da versão 0.0.3

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera-app#8]

**Comment by evertonkrystian** [comment]
Esta build foi criada e seria a mesma que podemos baixar em: https://play.google.com/store/apps/details?id=br.org.redelivre.delibera  ?

**Comment by cabelotaina** [comment]
Atualmente nao estamos com a build mais neste versao, tivemos que mudar a tecnologia envolvida no processo de autenticacao, sendo assim caimos para a versao 0.0.1, que ainda nao foi publicada na playstore, mas deve ser publicada nos proximos dias.
